name: WDIO Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  STANDART_LOGIN: ${{ secrets.STANDART_LOGIN }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install E2E dependencies
        run: npm install

      - name: Install ChromeDriver & GeckoDriver
        run: |
          npm install --global chromedriver geckodriver

      - name: Start Xvfb (Headless Display)
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 & export DISPLAY=:99

      - name: Run WebDriver tests
        run: |
          export DISPLAY=:99
          npm run wdio
        working-directory: e2e

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
